### PR TITLE
OTC-1016: claim insuree perms added

### PR DESCRIPTION
**Pull request by lruzicki**
TIcket:
https://openimis.atlassian.net/browse/OTC-1016

Changes:
- added claim perms check for insuree search in Claim panel

### CODE REVIEW

**Comment by wzglinieckisoldevelo** [comment]
LGTM

**Review by sniedzielski — APPROVED** [review]
LGTM

**Comment by delcroip** [comment]
I am not found of that solution, 
it might give too much rights to claims admin

**Comment by dborowiecki** [comment]
@lruzicki I think it;ll be better to add missing rights for the roles that require them instead of putting claim check in the insurees (it is looks intuitive  and in terms of modularity claims should depend on insurees therefore in insuree modules we shouldn't reference claims).

**Comment by lruzicki** [comment]
@dborowiecki I don't think that we can add this permissions to a role. Jiri mentioned that there should be a possibility to create roles so some user that will select all of the "Claims" role should be able to use all of the Claims functions. Creation form (front/claim/healthFacilities/claim) uses query from insuree module.

**Comment by dragos-dobre** [comment]
@lruzicki I don't like the solution because it makes a strong dependency between Insuree and Claim modules. openIMIS could be used as a Client Registry without using Claim module. Using only Claim could not be possible as you need an Insuree.  You can have a parameter to check the authorities that is true by default. Get Insuree data from Claim already checks authorities 
https://github.com/openimis/openimis-be-claim_py/blob/2f8d351b93ef20c5786eb0b0ac1272392e0771b5/claim/gql_queries.py#L61 
Otherwise please propose a solution. 
CC: @delcroip @dborowiecki

**Comment by lruzicki** [comment]
@dragos-dobre 
Yeah, this issue is handled in other PR by adding new query that searches for limited data so I will just close this PR since there is no point for those changes now.

**Pull request closed without merging**
